### ISSUE TITLE
Change font for heading..

### ISSUE THREAD

**Issue by VinnieBaz** [Kaptensanders/skolmat#1]
I´m new to both Github and HomeAssistant so apologise if I'm doing this wrong.. But would it be possible to change the font of the heading to something more readable/common? The current font is nice but not so child friendly.

**Comment by Kaptensanders** [comment]
could be configurable perhaps... I'll take a look next time I get into the code

**Comment by Svampsi** [comment]
Any news on this? Would be great if we could adjust the font on the header, either directly in the card or using card-mod

**Comment by Kaptensanders** [comment]
Added to 1.2.0 release

**Comment by Svampsi** [comment]
HUGE thanks!
