### ISSUE TITLE
Adding other subdomains of Mashie

### ISSUE THREAD

**Issue by lwalegba** [Kaptensanders/skolmat#10]
Hi

This is a suggestion for further development of this integration.

There are some schools that are using this type of URL:
https://sodexo.mashie.com/public/app/Akademikrogen%20skolor/d47bc6bf
As far as I can see it's exactly the same API as mpi.mashie.com. But I can't add it as a sensor, I assume it's because the integration doesn't recognize the URL.

Would it be possible to add sodexo.mashie.com as a supported API for this integration? I don't know if there are other subdomains that would also be usable.

**Comment by Kaptensanders** [comment]
oki, Il'l check it out. Hang on

**Comment by Kaptensanders** [comment]
yes you are right, seems to be the same. Check the 1.5.0 update

**Comment by lwalegba** [comment]
That is great news, thank you - from me and many parents in the Kalmar-region.
