### ISSUE TITLE
Different RSS feed?

### ISSUE THREAD

**Issue by fsundman73** [Kaptensanders/skolmat#11]
Hi,
My kids school use api.mashie.com but has a different look that your example from Laholm. 
https://mpi.mashie.com/public/menu/vallentuna+kommun/10b58ecf

I can't figure out how to enable debug logging for "skolmat" so maybe I'm doing something stupid here.
I just added this to my configuration.yaml:

  - platform: skolmat
    name: Bällstabergsskolan
    url: "https://mpi.mashie.com/public/menu/vallentuna+kommun/10b58ecf"

When checking the entity with the developer tool, I get the following:
calendar: {}
name: Bällstabergsskolan
icon: mdi:food
friendly_name: Bällstabergsskolan

Guess it can't read the content on the page...

Output from your card:
Bällstabergsskolan Meny v36
Det finns ingen meny för vecka 36

Best regards,
Fredrik

**Comment by Kaptensanders** [comment]
Hi, yes stupid mashie does not use any sensible datasource so the pages have to be scraped, meaning I have no way of knowing all the ways they will render a page. Hopefully not too many different ways. I'll look into this and push a fix.
/A

**Comment by fsundman73** [comment]
Thanks, let me know if I can help you in some way.
Best regards,
Fredrik

**Comment by Kaptensanders** [comment]
ok check the 1.5.0 update and let me know
/Anders

**Comment by fsundman73** [comment]
Thanks a lot!
Works great!
Best regards,
Fredrik
