### ISSUE TITLE
Matilda/webmenu.foodit.se

### ISSUE THREAD

**Issue by mickeblge** [Kaptensanders/skolmat#3]
Hello,

If you got the time and will, I would be thrilled if you also integrated the menues from webmenu.foodit.se or maybe creates a similar integration for this :)
They also use rss-feeds but I don't know how to program.. I've tried to fetch the menu in your "skolmat" integration but no luck :(

Yours sincerely
Micke

**Comment by Kaptensanders** [comment]
Hi Micke, sure, I didn't know about Matilda. I'll let you know when done

**Comment by Kaptensanders** [comment]
Update to 1.2.0 to use. I don't use matilda myself so please report if something goes wrong
br Anders

**Comment by mickeblge** [comment]
Hello,

The italic font is now showing up as it should on my IPhone :)
It repaired it self somehow :)

/Micke
________________________________
Från: Micke Andersson ***@***.***>
Skickat: Tuesday, August 30, 2022 12:09:07 AM
Till: Kaptensanders/skolmat ***@***.***>; Kaptensanders/skolmat ***@***.***>
Kopia: Author ***@***.***>
Ämne: Re: [Kaptensanders/skolmat] Matilda/webmenu.foodit.se (Issue #3)

Hello,

Works great 😊
Nice job!

Is it possible to show only todays meal? I’ve tried day, days, weekday and weekdays in the Lovelace card :( On the web I can use Day instead if Week in the address to show todays/weeks lunch. It gets messy in the configuration file (and funny titles on the name of the school in Lovelace) if I add an additional sensor, one for Week and one for Day on both schools :)

The custom lovelace card, skolmat, looks great on my pc and on my android tablet but in my iPhone 12 Pro Max the nice italic letters shows up as regular font.. see picture :)

/Micke
________________________________
Från: Kaptensanders ***@***.***>
Skickat: Monday, August 29, 2022 10:59:18 PM
Till: Kaptensanders/skolmat ***@***.***>
Kopia: mickeblge ***@***.***>; Author ***@***.***>
Ämne: Re: [Kaptensanders/skolmat] Matilda/webmenu.foodit.se (Issue #3)


Update to 1.2.0 to use. I don't use matilda myself so please report if something goes wrong
br Anders

**Comment by Kaptensanders** [comment]
![image](https://user-images.githubusercontent.com/24979195/187517744-1d52cca2-1171-4ac4-9454-245a42d5ac83.png)

Sure, you can configure the lovelace card to look like this with 

```
      - type: custom:skolmat-card
        entity: skolmat.skutehagen
        menu_type: today

```
in your Lovelace config. "menu_type: today"
if it is not working you might want to check that the UI is properly reloaded after the conf change

**Comment by mickeblge** [comment]
Aha, so easy 🙄
________________________________
Från: Kaptensanders ***@***.***>
Skickat: Tuesday, August 30, 2022 8:47:24 PM
Till: Kaptensanders/skolmat ***@***.***>
Kopia: mickeblge ***@***.***>; Author ***@***.***>
Ämne: Re: [Kaptensanders/skolmat] Matilda/webmenu.foodit.se (Issue #3)


[image]<https://user-images.githubusercontent.com/24979195/187517744-1d52cca2-1171-4ac4-9454-245a42d5ac83.png>

Sure, you can configure the lovelace card to look like this with

      - type: custom:skolmat-card
        entity: skolmat.skutehagen
        menu_type: today



in your Lovelace config. "menu_type: today"
if it is not working you might want to check that the UI is properly reloaded after the conf change

**Comment by mickeblge** [comment]
Hello,

Works great 😊
Nice job!

Is it possible to show only todays meal? I’ve tried day, days, weekday and weekdays in the Lovelace card :( On the web I can use Day instead if Week in the address to show todays/weeks lunch. It gets messy in the configuration file (and funny titles on the name of the school in Lovelace) if I add an additional sensor, one for Week and one for Day on both schools :)

The custom lovelace card, skolmat, looks great on my pc and on my android tablet but in my iPhone 12 Pro Max the nice italic letters shows up as regular font.. see picture :)

/Micke
________________________________
Från: Kaptensanders ***@***.***>
Skickat: Monday, August 29, 2022 10:59:18 PM
Till: Kaptensanders/skolmat ***@***.***>
Kopia: mickeblge ***@***.***>; Author ***@***.***>
Ämne: Re: [Kaptensanders/skolmat] Matilda/webmenu.foodit.se (Issue #3)


Update to 1.2.0 to use. I don't use matilda myself so please report if something goes wrong
br Anders
