### ISSUE TITLE
Sensor suddenly missing

### ISSUE THREAD

**Issue by ctankep23** [Kaptensanders/skolmat#5]
I noticed that the skolmat card/integration isnt working anymore and ive got a HA notification saying:

"The following integrations and platforms could not be set up:
[sensor.skolmat](https://github.com/Kaptensanders/skolmat) ([Show logs](http://homeassistant.local:8123/config/logs?filter=sensor.skolmat))"

But there is nothing logged. I do not know when it broke, but I haven't touched anything in my HA the last 6 months at least. sensor.skolmat just doesn't exist, but its there in my config.yaml, and as I said, I have touched nothing, so maybe it happened with one of the core updates, though I would think others would have experienced the same breakage..

**Comment by Kaptensanders** [comment]
Hi, hmm tough one, there was a breaking change in HA sometime before summer and I put out a fix for that. Maybe you are on the latest skolmat version but the old HA? Should be bw compatible though, or it was meant to anyway... But I have not heard this from anyone else...

**Comment by ChristianNiklasson** [comment]
The entity has disappeared after the last HA update, tried reinstall and double and tripple check the config file but can't se any issues...

**Comment by ChristianNiklasson** [comment]
Uppdate:

Seems to be intermittent error....
Sometimes it says not found and a couple of hours later it works fine again

**Comment by Kaptensanders** [comment]
Hi Christian, tricky to address. I'm on latest HA 2023.2.2 and have seen no issues so far. Let's see if someone else experience the same issues, or get back if you get some more insights
