### ISSUE TITLE
Stoped working after address change

### ISSUE THREAD

**Issue by LooMarcus** [Kaptensanders/skolmat#8]
Hi i have used this integration with the address type https://webmenu.foodit.se/ but now my school has change and uses https://menu.matildaplatform.com/meals/week/ is it possible to add so we can use that address?

**Comment by Kaptensanders** [comment]
Hi, seems Matilda are introducing something new. I'll take a look at it!
/Anders

**Comment by Kaptensanders** [comment]
Hi LooMarcus, update and try it now with the new url. Let me know what u think
/A

**Comment by LooMarcus** [comment]
> Hi LooMarcus, update and try it now with the new url. Let me know what u think /A

Hi, tried it now and its working again, thanks!
