### ISSUE TITLE
Additionall website 

### ISSUE THREAD

**Issue by churtbeullar** [Kaptensanders/skolmat#9]
I love this application. Unfortunately, my municipality changed the provider of the API to "Mashie". Is it possible to add this API also as optional in the application? The mashie-app/API is on this url; https://mpi.mashie.com/public/app

**Comment by Kaptensanders** [comment]
Hi, yes sure. I'll let you know when it up. Seems this one needs to be scraped off the page :/
/Anders

**Comment by Kaptensanders** [comment]
Hi, try updating to 1.4 and let me know how it works.
/Anders

**Comment by churtbeullar** [comment]
Works like a charm. Thank you so much!

**Comment by emigrating** [comment]
> 

Well, I mean, it grabs the menu for a couple weeks and stores it as an attribute but from what I can tell there's no sensor data available telling me what's being served today??

My TTL morning briefing just says "ingen mat" for the school I'm tracking using mashie.

**Comment by Kaptensanders** [comment]
> > 
> 
> Well, I mean, it grabs the menu for a couple weeks and stores it as an attribute but from what I can tell there's no sensor data available telling me what's being served today??
> 
> My TTL morning briefing just says "ingen mat" for the school I'm tracking using mashie.

My bad, check the update

**Comment by emigrating** [comment]
> > > 
> > 
> > 
> > Well, I mean, it grabs the menu for a couple weeks and stores it as an attribute but from what I can tell there's no sensor data available telling me what's being served today??
> > My TTL morning briefing just says "ingen mat" for the school I'm tracking using mashie.
> 
> My bad, check the update

Nice one mate. Saved me from delving in myself :) I may still reach out with a PR at some point though.

Now if only I could get Alexa to speak swedish without sounding like a complete idiot that'd be awesome.
